// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/g-villarinho/user-demo/internal/domain"
	"github.com/g-villarinho/user-demo/internal/model"
	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewAuthServiceMock creates a new instance of AuthServiceMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAuthServiceMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *AuthServiceMock {
	mock := &AuthServiceMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// AuthServiceMock is an autogenerated mock type for the AuthService type
type AuthServiceMock struct {
	mock.Mock
}

type AuthServiceMock_Expecter struct {
	mock *mock.Mock
}

func (_m *AuthServiceMock) EXPECT() *AuthServiceMock_Expecter {
	return &AuthServiceMock_Expecter{mock: &_m.Mock}
}

// ChangeEmail provides a mock function for the type AuthServiceMock
func (_mock *AuthServiceMock) ChangeEmail(ctx context.Context, token string) error {
	ret := _mock.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for ChangeEmail")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, token)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// AuthServiceMock_ChangeEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ChangeEmail'
type AuthServiceMock_ChangeEmail_Call struct {
	*mock.Call
}

// ChangeEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
func (_e *AuthServiceMock_Expecter) ChangeEmail(ctx interface{}, token interface{}) *AuthServiceMock_ChangeEmail_Call {
	return &AuthServiceMock_ChangeEmail_Call{Call: _e.mock.On("ChangeEmail", ctx, token)}
}

func (_c *AuthServiceMock_ChangeEmail_Call) Run(run func(ctx context.Context, token string)) *AuthServiceMock_ChangeEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *AuthServiceMock_ChangeEmail_Call) Return(err error) *AuthServiceMock_ChangeEmail_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *AuthServiceMock_ChangeEmail_Call) RunAndReturn(run func(ctx context.Context, token string) error) *AuthServiceMock_ChangeEmail_Call {
	_c.Call.Return(run)
	return _c
}

// Login provides a mock function for the type AuthServiceMock
func (_mock *AuthServiceMock) Login(ctx context.Context, input model.LoginInput) (*domain.Session, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 *domain.Session
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.LoginInput) (*domain.Session, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.LoginInput) *domain.Session); ok {
		r0 = returnFunc(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Session)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, model.LoginInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// AuthServiceMock_Login_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Login'
type AuthServiceMock_Login_Call struct {
	*mock.Call
}

// Login is a helper method to define mock.On call
//   - ctx context.Context
//   - input model.LoginInput
func (_e *AuthServiceMock_Expecter) Login(ctx interface{}, input interface{}) *AuthServiceMock_Login_Call {
	return &AuthServiceMock_Login_Call{Call: _e.mock.On("Login", ctx, input)}
}

func (_c *AuthServiceMock_Login_Call) Run(run func(ctx context.Context, input model.LoginInput)) *AuthServiceMock_Login_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 model.LoginInput
		if args[1] != nil {
			arg1 = args[1].(model.LoginInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *AuthServiceMock_Login_Call) Return(session *domain.Session, err error) *AuthServiceMock_Login_Call {
	_c.Call.Return(session, err)
	return _c
}

func (_c *AuthServiceMock_Login_Call) RunAndReturn(run func(ctx context.Context, input model.LoginInput) (*domain.Session, error)) *AuthServiceMock_Login_Call {
	_c.Call.Return(run)
	return _c
}

// RegisterAccount provides a mock function for the type AuthServiceMock
func (_mock *AuthServiceMock) RegisterAccount(ctx context.Context, name string, email string, password string) error {
	ret := _mock.Called(ctx, name, email, password)

	if len(ret) == 0 {
		panic("no return value specified for RegisterAccount")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = returnFunc(ctx, name, email, password)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// AuthServiceMock_RegisterAccount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RegisterAccount'
type AuthServiceMock_RegisterAccount_Call struct {
	*mock.Call
}

// RegisterAccount is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - email string
//   - password string
func (_e *AuthServiceMock_Expecter) RegisterAccount(ctx interface{}, name interface{}, email interface{}, password interface{}) *AuthServiceMock_RegisterAccount_Call {
	return &AuthServiceMock_RegisterAccount_Call{Call: _e.mock.On("RegisterAccount", ctx, name, email, password)}
}

func (_c *AuthServiceMock_RegisterAccount_Call) Run(run func(ctx context.Context, name string, email string, password string)) *AuthServiceMock_RegisterAccount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *AuthServiceMock_RegisterAccount_Call) Return(err error) *AuthServiceMock_RegisterAccount_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *AuthServiceMock_RegisterAccount_Call) RunAndReturn(run func(ctx context.Context, name string, email string, password string) error) *AuthServiceMock_RegisterAccount_Call {
	_c.Call.Return(run)
	return _c
}

// RequestChangeEmail provides a mock function for the type AuthServiceMock
func (_mock *AuthServiceMock) RequestChangeEmail(ctx context.Context, userID uuid.UUID, newEmail string) error {
	ret := _mock.Called(ctx, userID, newEmail)

	if len(ret) == 0 {
		panic("no return value specified for RequestChangeEmail")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) error); ok {
		r0 = returnFunc(ctx, userID, newEmail)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// AuthServiceMock_RequestChangeEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RequestChangeEmail'
type AuthServiceMock_RequestChangeEmail_Call struct {
	*mock.Call
}

// RequestChangeEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - newEmail string
func (_e *AuthServiceMock_Expecter) RequestChangeEmail(ctx interface{}, userID interface{}, newEmail interface{}) *AuthServiceMock_RequestChangeEmail_Call {
	return &AuthServiceMock_RequestChangeEmail_Call{Call: _e.mock.On("RequestChangeEmail", ctx, userID, newEmail)}
}

func (_c *AuthServiceMock_RequestChangeEmail_Call) Run(run func(ctx context.Context, userID uuid.UUID, newEmail string)) *AuthServiceMock_RequestChangeEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *AuthServiceMock_RequestChangeEmail_Call) Return(err error) *AuthServiceMock_RequestChangeEmail_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *AuthServiceMock_RequestChangeEmail_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID, newEmail string) error) *AuthServiceMock_RequestChangeEmail_Call {
	_c.Call.Return(run)
	return _c
}

// RequestPasswordReset provides a mock function for the type AuthServiceMock
func (_mock *AuthServiceMock) RequestPasswordReset(ctx context.Context, email string) error {
	ret := _mock.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for RequestPasswordReset")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, email)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// AuthServiceMock_RequestPasswordReset_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RequestPasswordReset'
type AuthServiceMock_RequestPasswordReset_Call struct {
	*mock.Call
}

// RequestPasswordReset is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *AuthServiceMock_Expecter) RequestPasswordReset(ctx interface{}, email interface{}) *AuthServiceMock_RequestPasswordReset_Call {
	return &AuthServiceMock_RequestPasswordReset_Call{Call: _e.mock.On("RequestPasswordReset", ctx, email)}
}

func (_c *AuthServiceMock_RequestPasswordReset_Call) Run(run func(ctx context.Context, email string)) *AuthServiceMock_RequestPasswordReset_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *AuthServiceMock_RequestPasswordReset_Call) Return(err error) *AuthServiceMock_RequestPasswordReset_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *AuthServiceMock_RequestPasswordReset_Call) RunAndReturn(run func(ctx context.Context, email string) error) *AuthServiceMock_RequestPasswordReset_Call {
	_c.Call.Return(run)
	return _c
}

// ResetPassword provides a mock function for the type AuthServiceMock
func (_mock *AuthServiceMock) ResetPassword(ctx context.Context, token string, newPassword string) (*domain.Session, error) {
	ret := _mock.Called(ctx, token, newPassword)

	if len(ret) == 0 {
		panic("no return value specified for ResetPassword")
	}

	var r0 *domain.Session
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*domain.Session, error)); ok {
		return returnFunc(ctx, token, newPassword)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *domain.Session); ok {
		r0 = returnFunc(ctx, token, newPassword)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Session)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, token, newPassword)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// AuthServiceMock_ResetPassword_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ResetPassword'
type AuthServiceMock_ResetPassword_Call struct {
	*mock.Call
}

// ResetPassword is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
//   - newPassword string
func (_e *AuthServiceMock_Expecter) ResetPassword(ctx interface{}, token interface{}, newPassword interface{}) *AuthServiceMock_ResetPassword_Call {
	return &AuthServiceMock_ResetPassword_Call{Call: _e.mock.On("ResetPassword", ctx, token, newPassword)}
}

func (_c *AuthServiceMock_ResetPassword_Call) Run(run func(ctx context.Context, token string, newPassword string)) *AuthServiceMock_ResetPassword_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *AuthServiceMock_ResetPassword_Call) Return(session *domain.Session, err error) *AuthServiceMock_ResetPassword_Call {
	_c.Call.Return(session, err)
	return _c
}

func (_c *AuthServiceMock_ResetPassword_Call) RunAndReturn(run func(ctx context.Context, token string, newPassword string) (*domain.Session, error)) *AuthServiceMock_ResetPassword_Call {
	_c.Call.Return(run)
	return _c
}

// UpdatePassword provides a mock function for the type AuthServiceMock
func (_mock *AuthServiceMock) UpdatePassword(ctx context.Context, userID uuid.UUID, currentPassword string, newPassword string) error {
	ret := _mock.Called(ctx, userID, currentPassword, newPassword)

	if len(ret) == 0 {
		panic("no return value specified for UpdatePassword")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, string) error); ok {
		r0 = returnFunc(ctx, userID, currentPassword, newPassword)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// AuthServiceMock_UpdatePassword_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdatePassword'
type AuthServiceMock_UpdatePassword_Call struct {
	*mock.Call
}

// UpdatePassword is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - currentPassword string
//   - newPassword string
func (_e *AuthServiceMock_Expecter) UpdatePassword(ctx interface{}, userID interface{}, currentPassword interface{}, newPassword interface{}) *AuthServiceMock_UpdatePassword_Call {
	return &AuthServiceMock_UpdatePassword_Call{Call: _e.mock.On("UpdatePassword", ctx, userID, currentPassword, newPassword)}
}

func (_c *AuthServiceMock_UpdatePassword_Call) Run(run func(ctx context.Context, userID uuid.UUID, currentPassword string, newPassword string)) *AuthServiceMock_UpdatePassword_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *AuthServiceMock_UpdatePassword_Call) Return(err error) *AuthServiceMock_UpdatePassword_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *AuthServiceMock_UpdatePassword_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID, currentPassword string, newPassword string) error) *AuthServiceMock_UpdatePassword_Call {
	_c.Call.Return(run)
	return _c
}

// VerifyEmail provides a mock function for the type AuthServiceMock
func (_mock *AuthServiceMock) VerifyEmail(ctx context.Context, input model.VerifyEmailInput) (*domain.Session, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for VerifyEmail")
	}

	var r0 *domain.Session
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.VerifyEmailInput) (*domain.Session, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.VerifyEmailInput) *domain.Session); ok {
		r0 = returnFunc(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Session)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, model.VerifyEmailInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// AuthServiceMock_VerifyEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'VerifyEmail'
type AuthServiceMock_VerifyEmail_Call struct {
	*mock.Call
}

// VerifyEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - input model.VerifyEmailInput
func (_e *AuthServiceMock_Expecter) VerifyEmail(ctx interface{}, input interface{}) *AuthServiceMock_VerifyEmail_Call {
	return &AuthServiceMock_VerifyEmail_Call{Call: _e.mock.On("VerifyEmail", ctx, input)}
}

func (_c *AuthServiceMock_VerifyEmail_Call) Run(run func(ctx context.Context, input model.VerifyEmailInput)) *AuthServiceMock_VerifyEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 model.VerifyEmailInput
		if args[1] != nil {
			arg1 = args[1].(model.VerifyEmailInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *AuthServiceMock_VerifyEmail_Call) Return(session *domain.Session, err error) *AuthServiceMock_VerifyEmail_Call {
	_c.Call.Return(session, err)
	return _c
}

func (_c *AuthServiceMock_VerifyEmail_Call) RunAndReturn(run func(ctx context.Context, input model.VerifyEmailInput) (*domain.Session, error)) *AuthServiceMock_VerifyEmail_Call {
	_c.Call.Return(run)
	return _c
}
