// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/g-villarinho/user-demo/internal/domain"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// SessionServiceMock is an autogenerated mock type for the SessionService type
type SessionServiceMock struct {
	mock.Mock
}

type SessionServiceMock_Expecter struct {
	mock *mock.Mock
}

func (_m *SessionServiceMock) EXPECT() *SessionServiceMock_Expecter {
	return &SessionServiceMock_Expecter{mock: &_m.Mock}
}

// CreateSession provides a mock function with given fields: ctx, userID, ipAddress, deviceName, userAgent
func (_m *SessionServiceMock) CreateSession(ctx context.Context, userID uuid.UUID, ipAddress string, deviceName string, userAgent string) (*domain.Session, error) {
	ret := _m.Called(ctx, userID, ipAddress, deviceName, userAgent)

	if len(ret) == 0 {
		panic("no return value specified for CreateSession")
	}

	var r0 *domain.Session
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, string, string) (*domain.Session, error)); ok {
		return rf(ctx, userID, ipAddress, deviceName, userAgent)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, string, string) *domain.Session); ok {
		r0 = rf(ctx, userID, ipAddress, deviceName, userAgent)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Session)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, string, string, string) error); ok {
		r1 = rf(ctx, userID, ipAddress, deviceName, userAgent)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SessionServiceMock_CreateSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateSession'
type SessionServiceMock_CreateSession_Call struct {
	*mock.Call
}

// CreateSession is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - ipAddress string
//   - deviceName string
//   - userAgent string
func (_e *SessionServiceMock_Expecter) CreateSession(ctx interface{}, userID interface{}, ipAddress interface{}, deviceName interface{}, userAgent interface{}) *SessionServiceMock_CreateSession_Call {
	return &SessionServiceMock_CreateSession_Call{Call: _e.mock.On("CreateSession", ctx, userID, ipAddress, deviceName, userAgent)}
}

func (_c *SessionServiceMock_CreateSession_Call) Run(run func(ctx context.Context, userID uuid.UUID, ipAddress string, deviceName string, userAgent string)) *SessionServiceMock_CreateSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(string), args[3].(string), args[4].(string))
	})
	return _c
}

func (_c *SessionServiceMock_CreateSession_Call) Return(_a0 *domain.Session, _a1 error) *SessionServiceMock_CreateSession_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *SessionServiceMock_CreateSession_Call) RunAndReturn(run func(context.Context, uuid.UUID, string, string, string) (*domain.Session, error)) *SessionServiceMock_CreateSession_Call {
	_c.Call.Return(run)
	return _c
}

// NewSessionServiceMock creates a new instance of SessionServiceMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSessionServiceMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *SessionServiceMock {
	mock := &SessionServiceMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
