// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/g-villarinho/user-demo/internal/domain"
	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewSessionRepositoryMock creates a new instance of SessionRepositoryMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSessionRepositoryMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *SessionRepositoryMock {
	mock := &SessionRepositoryMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// SessionRepositoryMock is an autogenerated mock type for the SessionRepository type
type SessionRepositoryMock struct {
	mock.Mock
}

type SessionRepositoryMock_Expecter struct {
	mock *mock.Mock
}

func (_m *SessionRepositoryMock) EXPECT() *SessionRepositoryMock_Expecter {
	return &SessionRepositoryMock_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type SessionRepositoryMock
func (_mock *SessionRepositoryMock) Create(ctx context.Context, session *domain.Session) error {
	ret := _mock.Called(ctx, session)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.Session) error); ok {
		r0 = returnFunc(ctx, session)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// SessionRepositoryMock_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type SessionRepositoryMock_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - session *domain.Session
func (_e *SessionRepositoryMock_Expecter) Create(ctx interface{}, session interface{}) *SessionRepositoryMock_Create_Call {
	return &SessionRepositoryMock_Create_Call{Call: _e.mock.On("Create", ctx, session)}
}

func (_c *SessionRepositoryMock_Create_Call) Run(run func(ctx context.Context, session *domain.Session)) *SessionRepositoryMock_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.Session
		if args[1] != nil {
			arg1 = args[1].(*domain.Session)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *SessionRepositoryMock_Create_Call) Return(err error) *SessionRepositoryMock_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *SessionRepositoryMock_Create_Call) RunAndReturn(run func(ctx context.Context, session *domain.Session) error) *SessionRepositoryMock_Create_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteByID provides a mock function for the type SessionRepositoryMock
func (_mock *SessionRepositoryMock) DeleteByID(ctx context.Context, ID uuid.UUID) error {
	ret := _mock.Called(ctx, ID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteByID")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, ID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// SessionRepositoryMock_DeleteByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteByID'
type SessionRepositoryMock_DeleteByID_Call struct {
	*mock.Call
}

// DeleteByID is a helper method to define mock.On call
//   - ctx context.Context
//   - ID uuid.UUID
func (_e *SessionRepositoryMock_Expecter) DeleteByID(ctx interface{}, ID interface{}) *SessionRepositoryMock_DeleteByID_Call {
	return &SessionRepositoryMock_DeleteByID_Call{Call: _e.mock.On("DeleteByID", ctx, ID)}
}

func (_c *SessionRepositoryMock_DeleteByID_Call) Run(run func(ctx context.Context, ID uuid.UUID)) *SessionRepositoryMock_DeleteByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *SessionRepositoryMock_DeleteByID_Call) Return(err error) *SessionRepositoryMock_DeleteByID_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *SessionRepositoryMock_DeleteByID_Call) RunAndReturn(run func(ctx context.Context, ID uuid.UUID) error) *SessionRepositoryMock_DeleteByID_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteByUserID provides a mock function for the type SessionRepositoryMock
func (_mock *SessionRepositoryMock) DeleteByUserID(ctx context.Context, userID uuid.UUID) error {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteByUserID")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// SessionRepositoryMock_DeleteByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteByUserID'
type SessionRepositoryMock_DeleteByUserID_Call struct {
	*mock.Call
}

// DeleteByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *SessionRepositoryMock_Expecter) DeleteByUserID(ctx interface{}, userID interface{}) *SessionRepositoryMock_DeleteByUserID_Call {
	return &SessionRepositoryMock_DeleteByUserID_Call{Call: _e.mock.On("DeleteByUserID", ctx, userID)}
}

func (_c *SessionRepositoryMock_DeleteByUserID_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *SessionRepositoryMock_DeleteByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *SessionRepositoryMock_DeleteByUserID_Call) Return(err error) *SessionRepositoryMock_DeleteByUserID_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *SessionRepositoryMock_DeleteByUserID_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID) error) *SessionRepositoryMock_DeleteByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function for the type SessionRepositoryMock
func (_mock *SessionRepositoryMock) FindByID(ctx context.Context, ID uuid.UUID) (*domain.Session, error) {
	ret := _mock.Called(ctx, ID)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *domain.Session
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*domain.Session, error)); ok {
		return returnFunc(ctx, ID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *domain.Session); ok {
		r0 = returnFunc(ctx, ID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Session)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, ID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// SessionRepositoryMock_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type SessionRepositoryMock_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - ID uuid.UUID
func (_e *SessionRepositoryMock_Expecter) FindByID(ctx interface{}, ID interface{}) *SessionRepositoryMock_FindByID_Call {
	return &SessionRepositoryMock_FindByID_Call{Call: _e.mock.On("FindByID", ctx, ID)}
}

func (_c *SessionRepositoryMock_FindByID_Call) Run(run func(ctx context.Context, ID uuid.UUID)) *SessionRepositoryMock_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *SessionRepositoryMock_FindByID_Call) Return(session *domain.Session, err error) *SessionRepositoryMock_FindByID_Call {
	_c.Call.Return(session, err)
	return _c
}

func (_c *SessionRepositoryMock_FindByID_Call) RunAndReturn(run func(ctx context.Context, ID uuid.UUID) (*domain.Session, error)) *SessionRepositoryMock_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// FindByToken provides a mock function for the type SessionRepositoryMock
func (_mock *SessionRepositoryMock) FindByToken(ctx context.Context, token string) (*domain.Session, error) {
	ret := _mock.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for FindByToken")
	}

	var r0 *domain.Session
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*domain.Session, error)); ok {
		return returnFunc(ctx, token)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *domain.Session); ok {
		r0 = returnFunc(ctx, token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Session)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, token)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// SessionRepositoryMock_FindByToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByToken'
type SessionRepositoryMock_FindByToken_Call struct {
	*mock.Call
}

// FindByToken is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
func (_e *SessionRepositoryMock_Expecter) FindByToken(ctx interface{}, token interface{}) *SessionRepositoryMock_FindByToken_Call {
	return &SessionRepositoryMock_FindByToken_Call{Call: _e.mock.On("FindByToken", ctx, token)}
}

func (_c *SessionRepositoryMock_FindByToken_Call) Run(run func(ctx context.Context, token string)) *SessionRepositoryMock_FindByToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *SessionRepositoryMock_FindByToken_Call) Return(session *domain.Session, err error) *SessionRepositoryMock_FindByToken_Call {
	_c.Call.Return(session, err)
	return _c
}

func (_c *SessionRepositoryMock_FindByToken_Call) RunAndReturn(run func(ctx context.Context, token string) (*domain.Session, error)) *SessionRepositoryMock_FindByToken_Call {
	_c.Call.Return(run)
	return _c
}
