// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"time"
)

type Session struct {
	ID         string    `json:"id"`
	Token      string    `json:"token"`
	DeviceName string    `json:"device_name"`
	IpAddress  string    `json:"ip_address"`
	UserAgent  string    `json:"user_agent"`
	ExpiresAt  time.Time `json:"expires_at"`
	CreatedAt  time.Time `json:"created_at"`
	UserID     string    `json:"user_id"`
}

type User struct {
	ID               string     `json:"id"`
	Name             string     `json:"name"`
	Email            string     `json:"email"`
	Status           string     `json:"status"`
	PasswordHash     string     `json:"password_hash"`
	CreatedAt        time.Time  `json:"created_at"`
	UpdatedAt        *time.Time `json:"updated_at"`
	EmailConfirmedAt *time.Time `json:"email_confirmed_at"`
	BlockedAt        *time.Time `json:"blocked_at"`
}

type Verification struct {
	ID        string    `json:"id"`
	Flow      string    `json:"flow"`
	Token     string    `json:"token"`
	CreatedAt time.Time `json:"created_at"`
	ExpiresAt time.Time `json:"expires_at"`
	Payload   *string   `json:"payload"`
	UserID    string    `json:"user_id"`
}
