// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"
	"database/sql"
)

type Querier interface {
	BlockUser(ctx context.Context, arg BlockUserParams) (sql.Result, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) error
	CreateUser(ctx context.Context, arg CreateUserParams) error
	CreateVerification(ctx context.Context, arg CreateVerificationParams) error
	DeleteSessionByID(ctx context.Context, id string) (sql.Result, error)
	DeleteSessionsByUserExceptID(ctx context.Context, arg DeleteSessionsByUserExceptIDParams) (sql.Result, error)
	DeleteSessionsByUserID(ctx context.Context, userID string) (sql.Result, error)
	DeleteVerification(ctx context.Context, id string) (sql.Result, error)
	DeleteVerificationsByUserIDAndFlow(ctx context.Context, arg DeleteVerificationsByUserIDAndFlowParams) error
	ExistsByEmail(ctx context.Context, email string) (bool, error)
	FindSessionByID(ctx context.Context, id string) (Session, error)
	FindSessionByToken(ctx context.Context, token string) (Session, error)
	FindSessionsByUserID(ctx context.Context, arg FindSessionsByUserIDParams) ([]Session, error)
	FindUserByEmail(ctx context.Context, email string) (User, error)
	FindUserByID(ctx context.Context, id string) (User, error)
	FindValidVerificationByUserIDAndFlow(ctx context.Context, arg FindValidVerificationByUserIDAndFlowParams) (Verification, error)
	FindVerificationByID(ctx context.Context, id string) (Verification, error)
	FindVerificationByToken(ctx context.Context, token string) (Verification, error)
	UpdateUserEmail(ctx context.Context, arg UpdateUserEmailParams) (sql.Result, error)
	UpdateUserName(ctx context.Context, arg UpdateUserNameParams) (sql.Result, error)
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) (sql.Result, error)
	VerifyUserEmail(ctx context.Context, arg VerifyUserEmailParams) (sql.Result, error)
}

var _ Querier = (*Queries)(nil)
