// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"
)

const blockUser = `-- name: BlockUser :execresult
UPDATE users
SET status = 'BLOCKED',
    updated_at = ?,
    blocked_at = ?
WHERE id = ?
`

type BlockUserParams struct {
	UpdatedAt *time.Time `json:"updated_at"`
	BlockedAt *time.Time `json:"blocked_at"`
	ID        string     `json:"id"`
}

func (q *Queries) BlockUser(ctx context.Context, arg BlockUserParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, blockUser, arg.UpdatedAt, arg.BlockedAt, arg.ID)
}

const createUser = `-- name: CreateUser :exec
INSERT INTO users (id, name, email, status, password_hash, created_at, updated_at, email_confirmed_at, blocked_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateUserParams struct {
	ID               string     `json:"id"`
	Name             string     `json:"name"`
	Email            string     `json:"email"`
	Status           string     `json:"status"`
	PasswordHash     string     `json:"password_hash"`
	CreatedAt        time.Time  `json:"created_at"`
	UpdatedAt        *time.Time `json:"updated_at"`
	EmailConfirmedAt *time.Time `json:"email_confirmed_at"`
	BlockedAt        *time.Time `json:"blocked_at"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.ExecContext(ctx, createUser,
		arg.ID,
		arg.Name,
		arg.Email,
		arg.Status,
		arg.PasswordHash,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.EmailConfirmedAt,
		arg.BlockedAt,
	)
	return err
}

const existsByEmail = `-- name: ExistsByEmail :one
SELECT COUNT(*) > 0 FROM users WHERE email = ?
`

func (q *Queries) ExistsByEmail(ctx context.Context, email string) (bool, error) {
	row := q.db.QueryRowContext(ctx, existsByEmail, email)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const findUserByEmail = `-- name: FindUserByEmail :one
SELECT id, name, email, status, password_hash, created_at, updated_at, email_confirmed_at, blocked_at FROM users WHERE email = ?
`

func (q *Queries) FindUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, findUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Status,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EmailConfirmedAt,
		&i.BlockedAt,
	)
	return i, err
}

const findUserByID = `-- name: FindUserByID :one
SELECT id, name, email, status, password_hash, created_at, updated_at, email_confirmed_at, blocked_at FROM users WHERE id = ?
`

func (q *Queries) FindUserByID(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRowContext(ctx, findUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Status,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EmailConfirmedAt,
		&i.BlockedAt,
	)
	return i, err
}

const updateUserEmail = `-- name: UpdateUserEmail :execresult
UPDATE users
SET email = ?, updated_at = ?
WHERE id = ?
`

type UpdateUserEmailParams struct {
	Email     string     `json:"email"`
	UpdatedAt *time.Time `json:"updated_at"`
	ID        string     `json:"id"`
}

func (q *Queries) UpdateUserEmail(ctx context.Context, arg UpdateUserEmailParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateUserEmail, arg.Email, arg.UpdatedAt, arg.ID)
}

const updateUserName = `-- name: UpdateUserName :execresult
UPDATE users
SET name = ?, updated_at = ?
WHERE id = ?
`

type UpdateUserNameParams struct {
	Name      string     `json:"name"`
	UpdatedAt *time.Time `json:"updated_at"`
	ID        string     `json:"id"`
}

func (q *Queries) UpdateUserName(ctx context.Context, arg UpdateUserNameParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateUserName, arg.Name, arg.UpdatedAt, arg.ID)
}

const updateUserPassword = `-- name: UpdateUserPassword :execresult
UPDATE users
SET password_hash = ?, updated_at = ?
WHERE id = ?
`

type UpdateUserPasswordParams struct {
	PasswordHash string     `json:"password_hash"`
	UpdatedAt    *time.Time `json:"updated_at"`
	ID           string     `json:"id"`
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateUserPassword, arg.PasswordHash, arg.UpdatedAt, arg.ID)
}

const verifyUserEmail = `-- name: VerifyUserEmail :execresult
UPDATE users
SET status = 'ACTIVE',
    updated_at = ?,
    email_confirmed_at = ?
WHERE id = ?
`

type VerifyUserEmailParams struct {
	UpdatedAt        *time.Time `json:"updated_at"`
	EmailConfirmedAt *time.Time `json:"email_confirmed_at"`
	ID               string     `json:"id"`
}

func (q *Queries) VerifyUserEmail(ctx context.Context, arg VerifyUserEmailParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, verifyUserEmail, arg.UpdatedAt, arg.EmailConfirmedAt, arg.ID)
}
