// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: verifications.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"
)

const createVerification = `-- name: CreateVerification :exec
INSERT INTO verifications (id, flow, token, created_at, expires_at, payload, user_id)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type CreateVerificationParams struct {
	ID        string    `json:"id"`
	Flow      string    `json:"flow"`
	Token     string    `json:"token"`
	CreatedAt time.Time `json:"created_at"`
	ExpiresAt time.Time `json:"expires_at"`
	Payload   *string   `json:"payload"`
	UserID    string    `json:"user_id"`
}

func (q *Queries) CreateVerification(ctx context.Context, arg CreateVerificationParams) error {
	_, err := q.db.ExecContext(ctx, createVerification,
		arg.ID,
		arg.Flow,
		arg.Token,
		arg.CreatedAt,
		arg.ExpiresAt,
		arg.Payload,
		arg.UserID,
	)
	return err
}

const deleteVerification = `-- name: DeleteVerification :execresult
DELETE FROM verifications WHERE id = ?
`

func (q *Queries) DeleteVerification(ctx context.Context, id string) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteVerification, id)
}

const deleteVerificationsByUserIDAndFlow = `-- name: DeleteVerificationsByUserIDAndFlow :exec
DELETE FROM verifications
WHERE user_id = ?
  AND flow = ?
  AND expires_at > ?
`

type DeleteVerificationsByUserIDAndFlowParams struct {
	UserID    string    `json:"user_id"`
	Flow      string    `json:"flow"`
	ExpiresAt time.Time `json:"expires_at"`
}

func (q *Queries) DeleteVerificationsByUserIDAndFlow(ctx context.Context, arg DeleteVerificationsByUserIDAndFlowParams) error {
	_, err := q.db.ExecContext(ctx, deleteVerificationsByUserIDAndFlow, arg.UserID, arg.Flow, arg.ExpiresAt)
	return err
}

const findValidVerificationByUserIDAndFlow = `-- name: FindValidVerificationByUserIDAndFlow :one
SELECT id, flow, token, created_at, expires_at, payload, user_id FROM verifications
WHERE user_id = ?
  AND flow = ?
  AND expires_at > ?
ORDER BY created_at DESC
LIMIT 1
`

type FindValidVerificationByUserIDAndFlowParams struct {
	UserID    string    `json:"user_id"`
	Flow      string    `json:"flow"`
	ExpiresAt time.Time `json:"expires_at"`
}

func (q *Queries) FindValidVerificationByUserIDAndFlow(ctx context.Context, arg FindValidVerificationByUserIDAndFlowParams) (Verification, error) {
	row := q.db.QueryRowContext(ctx, findValidVerificationByUserIDAndFlow, arg.UserID, arg.Flow, arg.ExpiresAt)
	var i Verification
	err := row.Scan(
		&i.ID,
		&i.Flow,
		&i.Token,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.Payload,
		&i.UserID,
	)
	return i, err
}

const findVerificationByID = `-- name: FindVerificationByID :one
SELECT id, flow, token, created_at, expires_at, payload, user_id FROM verifications WHERE id = ?
`

func (q *Queries) FindVerificationByID(ctx context.Context, id string) (Verification, error) {
	row := q.db.QueryRowContext(ctx, findVerificationByID, id)
	var i Verification
	err := row.Scan(
		&i.ID,
		&i.Flow,
		&i.Token,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.Payload,
		&i.UserID,
	)
	return i, err
}

const findVerificationByToken = `-- name: FindVerificationByToken :one
SELECT id, flow, token, created_at, expires_at, payload, user_id FROM verifications WHERE token = ?
`

func (q *Queries) FindVerificationByToken(ctx context.Context, token string) (Verification, error) {
	row := q.db.QueryRowContext(ctx, findVerificationByToken, token)
	var i Verification
	err := row.Scan(
		&i.ID,
		&i.Flow,
		&i.Token,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.Payload,
		&i.UserID,
	)
	return i, err
}
